contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
baseurl = "https://bauzer.github.io/"
title = "log bauzer"
languageCode = "ja-jp"
theme = "hugo-zen"
canonifyurls = true

[params]
  logo      = "/images/logo.png"
  twitter   = "https://twitter.com/BAUZERMETAL"
  github    = "https://github.com/bauzer/"
  email     = "bauzerboh@gmail.com"
  author    = "bauzer"
